HewlettPackard/cmf

.gitignore

This file is almost 100% based on [this template](https://github.com/github/gitignore/blob/main/Python.gitignore).

First commit of the `.gitignore` file.

---

cmflib/cmf.py

Added dvc import in cmf.py without that in jupyter lab environment getting into some weird issues

Added dvc import in cmf.py 

---

examples/al_object_detection/dvc_full_train.yaml
examples/al_object_detection/train.py

Python training code with discriminator training removed.

Full training- python code and dvc.yaml

---

cmflib/commands/metadata/push.py
server/Dockerfile
server/app/get_data.py
server/app/main.py
server/app/query_visualization.py
server/app/template/artifact_by_type.html
server/app/template/artifacts.html
server/app/template/home.html
server/app/template/lineage.html
server/app/template/list_of_pipelines.html
server/requirements.txt

lineage functionality

---

ui/src/App.js
ui/src/components/ArtifactTable/index.jsx
ui/src/components/ExecutionTable/index.jsx
ui/src/pages/artifacts/ArtifactTypeSidebar.jsx
ui/src/pages/artifacts/index.jsx

horizontal tab issue fixed

---

server/app/get_data.py
ui/src/components/ArtifactTable/index.css
ui/src/components/ArtifactTable/index.jsx
ui/src/components/ExecutionTable/index.css
ui/src/components/ExecutionTable/index.jsx

pagination update

---

cmflib/cmf.py

Check the properties for its existence

---

pyproject.toml
setup.py

Version bump - update execution changes

---

cmflib/commands/metadata/pull.py

metadata pull change for file name.
uses.

metadata pull change for file name.

---

cmflib/commands/metadata/push.py
server/app/get_data.py

adding change to check if execution_uuid exists or not

---

cmflib/cmf.py
cmflib/cmf_merger.py
cmflib/metadata_helper.py

changes made in uuid 

---

docker-compose-server.yml
docs/cmf_server/cmf-server.md
server/app/main.py
ui/src/config.js

adding hostname dependency

---

examples/al_object_detection/cycle_select.py

NA
Modified cycle_select.py to create json files for the bbox coordinates.
uses.

Change bbox text files to json 

---

pyproject.toml

Added dependencies to pyproject.toml

---

test/Readme.md
test/client_test_suite.py
test/server_api_endpoints_test_suite.py

Pytest Framework bugs

---

server/app/get_data.py
server/app/main.py
server/app/query_visualization.py
server/app/query_visualization_ArtifactExecution.py
server/app/query_visualization_execution.py
ui/Dockerfile
ui/src/client.js
ui/src/components/LineageArtifacts/index.css
ui/src/components/LineageArtifacts/index.jsx
ui/src/components/LineageImage/index.jsx
ui/src/components/LineageSidebar/index.jsx
ui/src/pages/lineage/LineageTypeSidebar.jsx
ui/src/pages/lineage/index.jsx

lineage d3js visualization

---

cmflib/cmfquery.py
server/app/get_data.py
server/app/query_visualization.py
server/app/query_visualization_execution.py
ui/src/client.js
ui/src/components/ExecutionDropdown/index.css
ui/src/components/ExecutionDropdown/index.jsx
ui/src/components/LineageArtifacts/index.jsx
ui/src/pages/lineage/LineageTypeSidebar.jsx
ui/src/pages/lineage/index.jsx

Repair lineage

---

server/app/get_data.py

Fixed GUI bug

---

pyproject.toml
setup.py

Bumped up version

---

cmflib/commands/artifact/pull.py
cmflib/storage_backends/amazonS3_artifacts.py

Amazon s3 bugs

---

cmflib/cmf.py
cmflib/cmf_merger.py
cmflib/cmfquery.py
docs/api/public/cmf.md
docs/api/public/cmfquery.md
mkdocs.yaml

Commented and added cmf.py API's Documentation. Adding cmfquery API's documentation

---

cmflib/cmf.py

updating docs cmf.py 

---

docker-compose-server.yml
server/Dockerfile

Adding depends_on flag

---

docs/api/public/cmf.md

updating cmf docs alignment

---

cmflib/cmfquery.py
server/app/get_data.py
server/app/main.py
server/app/query_exec_lineage.py
server/app/query_visualization.py
server/app/query_visualization_execution.py
ui/src/client.js
ui/src/components/ExecutionDropdown/index.jsx
ui/src/pages/artifacts/index.jsx
ui/src/pages/executions/index.jsx
ui/src/pages/lineage/LineageTypeSidebar.jsx
ui/src/pages/lineage/index.jsx

Enhanced Artifacts lineage code to handle bigger mlmd files and implemented Execution lineage

---

server/app/main.py
server/app/query_exec_lineage.py
ui/src/components/LineageArtifacts/index.css
ui/src/components/LineageArtifacts/index.jsx
ui/src/pages/lineage/index.jsx

Gui visual enhancement

---

cmf_dvc_ingest.py
cmflib/cmf.py
pyproject.toml
setup.py

Rishabh patch 2

---

cmflib/cmf.py
pyproject.toml
setup.py

Reverted version to 0.0.8

---

cmflib/commands/metadata/push.py
cmflib/server_interface/server_interface.py
docker-compose-server.yml
server/Dockerfile
server/app/get_data.py
server/app/main.py
server/requirements.txt
ui/src/App.js
ui/src/components/DashboardHeader/index.jsx
ui/src/config.js
ui/src/pages/tensorboard/index.jsx

Tensorboard Integration

---

cmflib/bin/cmf_dvc_ingest.py
cmflib/cmf.py

updated create_execution and cmf_dvc_ingest

---

cmflib/bin/cmf_dvc_ingest.py
cmflib/cmf.py

Copyright added in cmf_dvc_ingest

---

cmflib/bin/cmf_dvc_ingest.py
cmflib/cmf.py
docker-compose-server.yml

Adding cmf init path

---

cmflib/bin/cmf_dvc_ingest.py
cmflib/dvc_wrapper.py

Added support for staging and pushing external files

---

server/app/main.py
server/app/query_artifact_tree_lineage.py
ui/src/client.js
ui/src/components/TangledTree/index.jsx
ui/src/pages/artifacts/index.jsx
ui/src/pages/lineage/index.jsx

adding artifact tree lineage

---

server/app/main.py
server/app/query_artifact_tree_lineage.py
ui/src/client.js
ui/src/pages/lineage/index.jsx

Artifact tree regression

---

cmflib/dvc_wrapper.py

Fix dvc wrapper

---

cmflib/cmf.py
server/app/main.py

Regression master branch

---

cmflib/cmf.py

Path branch

---

cmflib/cmf.py

Regression - The artifact_path was not qualified with class name 

---

cmflib/cmf_ray_logger.py
docs/api/public/cmf_ray_logger.md

Cmf ray logger

---

cmflib/cmf_ray_logger.py

Added features to cmf_ray_logger

---

cmflib/cmf_ray_logger.py
docs/api/public/cmf_ray_logger.md

model and dataset logging for raytune using CMF

---

cmflib/cli/__init__.py
cmflib/commands/metadata/export.py
cmflib/commands/repo/pull.py
cmflib/commands/repo/push.py
pyproject.toml
requirements.txt
setup.py

Facing an issue in the command line after merging the progress bar PR.
uses.

Regression in master branch

---

cmflib/cmf_merger.py
cmflib/commands/init/amazonS3.py
cmflib/commands/init/local.py
cmflib/commands/init/minioS3.py
cmflib/commands/init/osdfremote.py
cmflib/commands/init/sshremote.py
cmflib/commands/metadata/pull.py

Regression in master branch inside command line

---

cmflib/cmf.py
cmflib/cmf_server.py
cmflib/commands/metadata/push.py
cmflib/server_interface/server_interface.py
server/app/main.py
ui/src/components/ArtifactPTable/index.jsx

Fixing remaining features of labeling task

---

cmflib/commands/init/amazonS3.py

Regression in cmf init amazon command

---

cmflib/utils/helper_functions.py
custom-entrypoint.sh
docker-compose-server.yml
docs/cmf_server/cmf-server.md
docs/setup/index.md
server/app/db/dbconfig.py

fixed code so that user can pass any port for postgres

---

pyproject.toml
setup.py

pypi release at 0.94

---

server/app/db/dbmodels.py
server/app/db/dbqueries.py

Converted raw queries on metahub branch to SQLAlchemy Core

---

server/app/get_data.py

Regression in Master branch while doing metadata pull with execution UUID.

---

server/Dockerfile

CMF server Dockerfile: migrate CMF server base python image from slim-buster to slim-bullseye
